# Generated by Django 2.0.6 on 2018-06-26 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0025_user_field_codetoken'),
        ('users', '0012_social_auth_providers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('ip_address', models.CharField(max_length=50, verbose_name='IP address')),
                ('geo_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='geo location')),
                ('requesting_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_login_entries_as_requester', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='requesting app')),
                ('requesting_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_login_entries_as_requester', to='oidc_provider.Client', verbose_name='requesting client')),
                ('target_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_login_entries_as_target', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL, verbose_name='target app')),
                ('target_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_login_entries_as_target', to='oidc_provider.Client', verbose_name='target client')),
            ],
            options={
                'verbose_name': 'user login entry',
                'verbose_name_plural': 'user login entries',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='loginmethod',
            name='provider_id',
            field=models.CharField(choices=[('espoo_adfs', 'espoo_adfs'), ('facebook', 'facebook'), ('github', 'github'), ('google', 'google'), ('helsinki_adfs', 'helsinki_adfs'), ('yletunnus', 'yletunnus')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='userloginentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_entries', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterModelOptions(
            name='userloginentry',
            options={'ordering': ('id',), 'verbose_name': 'user login entry',
                     'verbose_name_plural': 'user login entries'},
        ),
    ]
