# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0022_auto_20170331_1626'),
        ('oidc_apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoConsentScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_consent_scopes', to='oidc_provider.Client', verbose_name='auto consent scope')),
            ],
            options={
                'verbose_name': 'Auto consent scope',
                'verbose_name_plural': 'Auto consent scope',
            },
        ),
        migrations.AlterUniqueTogether(
            name='autoconsentscope',
            unique_together=set([('scope', 'client')]),
        ),
    ]
